INSERT INTO dispositivos (id_tomb, tipo_de_disp, qnt_armaz, tipo_armaz, marca, funcionando, data_de_an, locat_do_disp, descricao, modelo) VALUES 
(816996598, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817010645, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817010599, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817000305, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(811753590, 'computador', '', '', 'lenovo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817010564, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(831454440, 'computador', '', '', 'positivo', 'nao', '02/12/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817008721, 'computador', '', '', 'positivo', 'nao', '02/12/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(830993517, 'computador', '', '', 'positivo', 'nao', '02/12/24', 'sala de manutencao, gex-juaz', 'fonte queimada', 'modelo_generico'),
(817028528, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'defeito na placa mae', 'modelo_generico'),
(817009469, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'defeito na placa mae', 'modelo_generico'),
(831009748, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(830611860, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(816997144, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(817214194, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(830539220, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(817000437, 'computador', '', '', 'positivo', 'nao', '29/11/24', 'sala de manutencao, gex-juaz', 'nao exibe imagem, mesmo com diferentes pentes de memoria', 'modelo_generico'),
(817028641, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817010998, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817028765, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817009116, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817009280, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817009213, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839273738, 'caixa de som', '', '', 'GWI', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817008802, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817007636, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817130357, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831025735, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(931027967, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831028337, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830608400, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831456779, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816993718, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817001336, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817008780, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830540903, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830608877, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830612815, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830610375, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830623329, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831483270, 'impressora', '', '', 'samsung', 'nao', '', 'sala de manutencao, gex-juaz', 'defeito na fonte, nao liga', 'modelo_generico'),
(831483342, 'impressora', '', '', 'samsung', 'nao', '', 'sala de manutencao, gex-juaz', 'defeito na fonte, nao liga', 'modelo_generico'),
(831483482, 'impressora', '', '', 'samsung', 'nao', '', 'sala de manutencao, gex-juaz', 'defeito na fonte, nao liga', 'modelo_generico'),
(831629673, 'switch', '', '', 'datacom', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(832652385, 'switch', '', '', '3com', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(832651516, 'switch', '', '', '3com', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(831449462, 'switch', '', '', 'D-link', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(831488883, 'switch', '', '', 'D-link', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(832693146, 'switch', '', '', 'datacom', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(839272804, 'caixa de som', '', '', 'GWI', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839257309, 'impressora', '', '', 'daruma', 'nao', '08/11/24', 'sala de manutencao, gex-juaz', 'defeito na placa mae', 'modelo_generico'),
(839267649, 'impressora', '', '', 'daruma', 'nao', '08/11/24', 'sala de manutencao, gex-juaz', 'defeito na entrada usb', 'modelo_generico'),
(832676039, 'impressora', '', '', 'daruma', 'nao', '08/11/24', 'sala de manutencao, gex-juaz', 'defeito na entrada usb', 'modelo_generico'),
(831496452, 'impressora', '', '', 'daruma', 'nao', '08/11/24', 'sala de manutencao, gex-juaz', 'defeito na placa mae', 'modelo_generico'),
(832680796, 'impressora', '', '', 'daruma', 'nao', '08/11/24', 'sala de manutencao, gex-juaz', 'defeito na placa mae', 'modelo_generico'),
(831628634, 'switch', '', '', 'datacom', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(831628677, 'switch', '', '', 'datacom', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(832657425, 'switch', '', '', 'Huawei', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(839263619, 'switch', '', '', 'Huawei', 'nao', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(831498510, 'impressora', '', '', 'samsung', 'nao', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817218033, 'impressora', '', '', 'samsung', 'nao', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817218297, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831431415, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830891447, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(817218084, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831483288, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831148420, 'monitor', '', '', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(831023279, 'computador', '240', 'ssd', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(839262990, 'monitor', '', '', 'lg', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(839265220, 'monitor', '', '', 'lg', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(816996873, 'computador', '', 'hd', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(817729305, 'computador', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831431423, 'impressora', '', '', 'samsung', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(832691160, 'monitor', '', '', 'lg', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(816869669, 'teclado', '', '', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(817211683, 'computador', '', '', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(817008900, 'computador', '', '', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(839263023, 'monitor', '', '', 'lg', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(832201502, 'teclado', '', '', 'positivo', 'sim', '04/12/24', 'sala de manutencao, gex-juaz', 'em perfeito estado de funcionamento', 'modelo_generico'),
(831624774, 'scanner', '', '', 'avision', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832652016, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832652032, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830934871, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(843978589, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832695343, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816778507, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839287658, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830935207, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832667218, 'monitor', '', '', 'lg', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831176962, 'monitor', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(804484945, 'telefone', '', '', 'siemens', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(804485062, 'telefone', '', '', 'siemens', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832201448, 'teclado', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816562164, 'monitor', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832695394, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839285736, 'estabilizador', '', '', 'enermax', 'nao', '', 'sala de manutencao, gex-juaz', 'danificado por queda', 'modelo_generico'),
(808519077, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830839259, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832700673, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839291914, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832679160, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(809154943, 'estabilizador', '', '', 'enermax', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832695351, 'estabilizador', '', '', 'sms', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832673188, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(830840915, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816790795, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816784035, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(816780471, 'teclado', '', '', 'positivo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839299052, 'monitor', '', '', 'lg', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839262841, 'monitor', '', '', 'lg', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832652369, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831498951, 'scanner', '', '', 'fujitsu', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831539267, 'impressora', '', '', 'samsung', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832694576, 'impressora', '', '', 'samsung', 'sim', '', 'sala de manutencao, gex-juaz', 'tonner em falta', 'modelo_generico'),
(832667188, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839257287, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832672971, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(839262485, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832691208, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832658880, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(832658260, 'computador', '', '', 'lenovo', '', '', 'sala de manutencao, gex-juaz', 'nao analisado', 'modelo_generico'),
(831008300, 'computador', '500', 'hd', 'positivo', 'sim', '25/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(831027487, 'computador', '500', 'hd', 'positivo', 'sim', '29/04/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(831028220, 'computador', '500', 'hd', 'positivo', 'sim', '02/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(830609482, 'computador', '500', 'hd', 'positivo', 'sim', '05/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(831000201, 'computador', '500', 'hd', 'positivo', 'sim', '06/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(831027894, 'computador', '500', 'hd', 'positivo', 'sim', '06/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w11', 'modelo_generico'),
(817006605, 'computador', '500', 'hd', 'positivo', 'sim', '03/12/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010912, 'computador', '500', 'hd', 'positivo', 'sim', '03/12/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817211799, 'computador', '500', 'hd', 'positivo', 'sim', '25/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816994528, 'computador', '500', 'hd', 'positivo', 'sim', '24/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816994650, 'computador', '500', 'hd', 'positivo', 'sim', '25/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817293341, 'computador', '320', 'hd', 'positivo', 'sim', '24/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817213465, 'computador', '320', 'hd', 'positivo', 'sim', '03/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817159258, 'computador', '160', 'hd', 'positivo', 'sim', '05/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816996539, 'computador', '500', 'hd', 'positivo', 'sim', '07/06/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817028587, 'computador', '310', 'hd', 'positivo', 'sim', '14/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817027769, 'computador', '320', 'hd', 'positivo', 'sim', '11/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817006958, 'computador', '320', 'hd', 'positivo', 'sim', '03/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817739173, 'computador', '500', 'hd', 'positivo', 'sim', '09/04/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817213333, 'computador', '500', 'hd', 'positivo', 'sim', '02/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010939, 'computador', '320', 'hd', 'positivo', 'sim', '29/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817159126, 'computador', '500', 'hd', 'positivo', 'sim', '19/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817001549, 'computador', '320', 'hd', 'positivo', 'sim', '07/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817008667, 'computador', '160', 'hd', 'positivo', 'sim', '05/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816994809, 'computador', '320', 'hd', 'positivo', 'sim', '22/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817027548, 'computador', '320', 'hd', 'positivo', 'sim', '07/04/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010718, 'computador', '500', 'hd', 'positivo', 'sim', '22/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817009140, 'computador', '160', 'hd', 'positivo', 'sim', '18/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816994749, 'computador', '500', 'hd', 'positivo', 'sim', '24/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010521, 'computador', '320', 'hd', 'positivo', 'sim', '24/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817008543, 'computador', '320', 'hd', 'positivo', 'sim', '19/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817130543, 'computador', '500', 'hd', 'positivo', 'sim', '31/05/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817022368, 'computador', '320', 'hd', 'positivo', 'sim', '02/12/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010696, 'computador', '500', 'hd', 'positivo', 'sim', '23/01/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817005420, 'computador', '500', 'hd', 'positivo', 'sim', '05/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817005578, 'computador', '320', 'hd', 'positivo', 'sim', '06/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817004394, 'computador', '320', 'hd', 'positivo', 'sim', '18/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817008799, 'computador', '320', 'hd', 'positivo', 'sim', '19/06/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(816994943, 'computador', '500', 'hd', 'positivo', 'sim', '18/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817727442, 'computador', '320', 'hd', 'positivo', 'sim', '18/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817027823, 'computador', '500', 'hd', 'positivo', 'sim', '14/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817028560, 'computador', '320', 'hd', 'positivo', 'sim', '03/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817214577, 'computador', '320', 'hd', 'positivo', 'sim', '25/03/22', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817211284, 'computador', '320', 'hd', 'positivo', 'sim', '04/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817214607, 'computador', '320', 'hd', 'positivo', 'sim', '29/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817010637, 'computador', '320', 'hd', 'positivo', 'sim', '23/03/23', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817198873, 'computador', '320', 'hd', 'positivo', 'sim', '06/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817148540, 'computador', '320', 'hd', 'positivo', 'sim', '29/10/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817154400, 'computador', '320', 'hd', 'positivo', 'sim', '28/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817017976, 'computador', '160', 'hd', 'positivo', 'sim', '26/11/24', 'estoque/sala de videoconferencia, gex-juaz', 'defeito no vga', 'modelo_generico'),
(817008853, 'computador', '320', 'hd', 'positivo', 'sim', '02/12/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(817004475, 'computador', '500', 'hd', 'positivo', 'sim', '06/12/24', 'estoque/sala de videoconferencia, gex-juaz', 'w7', 'modelo_generico'),
(831569360, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', 'necessita troca de toner', 'modelo_generico'),
(832664103, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(817218270, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831533544, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831431555, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830891331, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831431474, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831623268, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', 'sem hd', 'modelo_generico'),
(830891358, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830891609, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816726434, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816562083, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832659509, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263171, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816562725, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832656496, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831150092, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830752188, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831164050, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831146656, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816556330, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263120, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839301022, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839300697, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832685968, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831177772, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831169842, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263252, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', 'apenas dvi funcionando', 'modelo_generico'),
(816561931, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(817747877, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816562741, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830635483, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839288042, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839300956, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816727155, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839274211, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816561656, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263724, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816766975, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263180, 'monitor', '', '', 'aoc', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832695297, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839263139, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831464631, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830755110, 'monitor', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831505206, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839282466, 'teclado', '', '', 'mitsuni', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816783012, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831343281, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816797269, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816786526, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(808685988, 'teclado', '', '', 'mitsuni', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830782770, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830783679, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816791660, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(808687727, 'teclado', '', '', 'mitsuni', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816782539, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816788561, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816794332, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831341025, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816797226, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832659452, 'monitor', '', '', 'infowey', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832677485, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832681644, 'monitor', '', '', 'lg', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830608338, 'computador', '500', 'hd', 'positivo', 'sim ', '26/02/24', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816790558, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832695432, 'monitor', '', '', 'lg', '', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(837213325, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817009175, 'computador', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(816795991, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816794545, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(816794367, 'teclado', '', '', 'positivo', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(817216289, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832677469, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832665851, 'computador', '', '', 'lenovo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(831533480, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831569379, 'impressora', '', '', 'samsung', 'sim ', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831431504, 'impressora', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(817009060, 'computador ', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817027971, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(831026863, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817213449, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817727462, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817028617, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817008829, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(830610103, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(817028773, 'computador', '', '', 'positivo', '', '', 'estoque/sala de videoconferencia, gex-juaz', 'nao analisado', 'modelo_generico'),
(831673443, 'scanner ', '', '', 'kodak', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831664355, 'scanner', '', '', 'kodak', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831629789, 'switch', '', '', 'datacom', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839257260, 'switch', '', '', '3com', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(843983345, 'switch', '', '', '3com', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830935070, 'scanner', '', '', 'fujitsu', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830935193, 'scanner', '', '', 'fujitsu', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(807425966, 'monitor', '', '', 'samsung', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832658421, 'estabilizador', '', '', 'enermax', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(808662988, 'estabilizador', '', '', 'enermax', 'sim ', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839265484, 'estabilizador', '', '', 'enermax', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(832655414, 'impressora', '', '', 'daruma', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839267657, 'impressora', '', '', 'daruma', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(839267665, 'impressora', '', '', 'daruma', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(830924434, 'impressora', '', '', 'daruma', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831453745, 'computador servidor', '', '', 'dell', 'sim', '', 'estoque/sala de videoconferencia, gex-juaz', '', 'modelo_generico'),
(831533609, 'impressora', '', '', 'samsung', 'sim', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico'),
(831533668, 'impressora', '', '', 'samsung', 'sim', '', 'sala de manutencao, gex-juaz', '', 'modelo_generico');