"""add estagiario column to dispositivos

Revision ID: 940449aaaf9b
Revises: 44325abe9fdf
Create Date: 2025-07-10 14:15:53.203499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940449aaaf9b'
down_revision: Union[str, None] = '44325abe9fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_opcoes_formulario_id'), table_name='opcoes_formulario')
    # op.drop_table('opcoes_formulario')
    # Colunas já adicionadas na criação inicial; nada a fazer.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nenhuma alteração feita no upgrade.
    pass
    op.create_table('opcoes_formulario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('valor', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor', name=op.f('uix_tipo_valor'))
    )
    op.create_index(op.f('ix_opcoes_formulario_id'), 'opcoes_formulario', ['id'], unique=False)
    # ### end Alembic commands ###
