"""Adiciona tabelas de dispositivos e logs

Revision ID: d9125a2e0e74
Revises: 
Create Date: 2025-04-08 09:05:12.427452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9125a2e0e74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    ### Upgrade schema.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id_tomb', sa.Integer(), nullable=False),
    sa.Column('tipo_de_disp', sa.String(length=50), nullable=False),
    sa.Column('qnt_ram', sa.Integer(), nullable=True),
    sa.Column('qnt_armaz', sa.Integer(), nullable=True),
    sa.Column('tipo_armaz', sa.String(length=10), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('funcionando', sa.Boolean(), nullable=True),
    sa.Column('data_de_an', sa.Date(), nullable=True),
    sa.Column('locat_do_disp', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estagiario', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_tomb')
    )
    op.create_index(op.f('ix_dispositivos_id_tomb'), 'dispositivos', ['id_tomb'], unique=False)
    op.create_table('outros_dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tomb', sa.Integer(), nullable=True),
    sa.Column('tipo_de_disp', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('funcionando', sa.Boolean(), nullable=True),
    sa.Column('data_de_an', sa.Date(), nullable=True),
    sa.Column('locat_do_disp', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('estagiario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_tomb')
    )
    op.create_index(op.f('ix_outros_dispositivos_id'), 'outros_dispositivos', ['id'], unique=False)
    op.create_index(op.f('ix_outros_dispositivos_id_tomb'), 'outros_dispositivos', ['id_tomb'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_table('log_atualizacoes',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tomb', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sa.String(length=50), nullable=True),
    sa.Column('valor_antigo', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('data_hora_alteracao', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_tomb'], ['dispositivos.id_tomb'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_log_atualizacoes_id_log'), 'log_atualizacoes', ['id_log'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    ### Downgrade schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_atualizacoes_id_log'), table_name='log_atualizacoes')
    op.drop_table('log_atualizacoes')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_outros_dispositivos_id_tomb'), table_name='outros_dispositivos')
    op.drop_index(op.f('ix_outros_dispositivos_id'), table_name='outros_dispositivos')
    op.drop_table('outros_dispositivos')
    op.drop_index(op.f('ix_dispositivos_id_tomb'), table_name='dispositivos')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###